### PR TITLE
update the readme please

### PR DESCRIPTION
**Pull request by Basshou**
It's very much important for you to update it so it would be much more accessible to a lot more people. Originally I was also planning to do it for the "#" as well, but it didn't really worked well as it would then remove the line break D:

### CODE REVIEW

**Comment by poseiso** [comment]
what kind of font does this one uses lmao my bare bone arch gave me curse of ra type of glyph 
image

**Comment by Basshou** [comment]
just merge it for the yolo

**Comment by poseiso** [comment]
append the english one instead of replacing it

**Comment by Basshou** [comment]
epic

**Pull request merged**
